apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-configmap
  namespace: {{ .Values.namespace }}
  labels:
    id: "19108294"
    app: maria
    env: dev
data:
  MYSQL_DATABASE: {{ .Values.configmap.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.configmap.MYSQL_USER }}
  
