apiVersion: v1
kind: Secret
metadata:
  name: maria-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD }}  # 'wordpress' in base64
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD }}       # 'wordpress' in base64
