apiVersion: v1
kind: Service
metadata:
  name: word-svc
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    id: "19108294"
    app: word
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

