apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: {{ .Values.service.namespace }}
  labels:
    id: "19108294"
    app: nginx-proxy
spec:
  type: {{ .Values.service.type }}
  selector:
    id: "19108294"
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
